AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  TagName:
    Type: String
    Description: TagName of your Infrastructure.
Resources:
  ApiGatewayCloudWatchLogsRole:
   Type: "AWS::IAM::Role"
   Properties:
     AssumeRolePolicyDocument:
       Version: "2012-10-17"
       Statement:
         - Effect: "Allow"
           Principal:
             Service:
               - "apigateway.amazonaws.com"
           Action: ['sts:AssumeRole']
  ApiGatewayCloudWatchLogsPolicy:
   Type: "AWS::IAM::Policy"
   Properties:
     PolicyName: "ApiGatewayLogsPolicy"
     PolicyDocument:
       Version: "2012-10-17"
       Statement:
         - Effect: "Allow"
           Action: ['logs:*']
           Resource: '*'
     Roles: [!Ref 'ApiGatewayCloudWatchLogsRole']
  ApiGatewayAccount:
   Type: "AWS::ApiGateway::Account"
   DependsOn: ApiGatewayCloudWatchLogsPolicy
   Properties:
     CloudWatchRoleArn:
       Fn::GetAtt:
         - "ApiGatewayCloudWatchLogsRole"
         - "Arn"
