  
  APIGateway:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/S3_BUCKET_NAME/templates/api-gateway/api-gateway.yaml
      Parameters:
        TagName: !Ref 'TagName'
